# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        poetry-version: [1.1.4]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Build package with poetry
        run: poetry build
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan tommy.snglth.space >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY  }}"
      - name: Copy built package to the host and install it
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          TMPDIR=$(ssh "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" mktemp)
          scp dist/*.whl "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}":/var/tmp/pkgs
          ssh "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" /var/www/restaurant/venv/bin/pip uninstall -y restaurant  # This is screwed
          ssh "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" /var/www/restaurant/venv/bin/pip install restaurant --no-index --find-links file:///var/tmp/pkgs  # This is also screwed
          ssh "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" sudo killall -HUP uwsgi

